package main

import "github.com/phifertoo/leetcode/exercises"

func main() {
	// heap := fox.MinHeap{}
	// fmt.Print(heap.HighestFreq([]int{1, 1, 1, 2, 2, 3}, 2))
	// exercises.Practice4Tester()
	// exercises.Practice3Tester()
	// exercises.PracticeTester()
	// exercises.FibonacciTester()
	// exercises.FactorialTester()
	// exercises.TopKFrequentTester()
	// exercises.FizzBuzzTester()
	// exercises.FirstUniqueCharacterTester()
	// exercises.IntersectionOfTwoArraysTester()
	// exercises.ReverseßStringTester()
	// exercises.PowerOfThreeTester()
	// exercises.MissingNumberTester()
	// exercises.IsValidAnagramTester()
	// exercises.IsLinkedListPalindromeTester()
	// exercises.ContainsDuplicateTester()
	// exercises.ReverseLinkedListTester()
	// exercises.HappyNumberTester()
	// exercises.Count1BitsTester()
	// exercises.ReserseBitsTester()
	// exercises.TitleToNumberTester()
	// exercises.MajorityElementTester()
	// exercises.HasCycleTester()
	// exercises.SingleNumberTester()
	// exercises.IsPalindrome2Tester()
	// exercises.MaxProfitTester()
	// exercises.PascalsTriangleTester()
	// exercises.SortedArrayToBSTTester()
	// exercises.MaxDepthTester()
	// exercises.IsSymmetricTester2()
	// exercises.IsSymmetricTester1()
	exercises.InorderTraversalTester()
	// exercises.SqrtTester()
	// exercises.AddBinaryTester()
	// exercises.PlusOneTester()
	// exercises.LengthOfLastWordTester()
	// exercises.SearchInsertTester()
	// exercises.IndexOfFirstOccuranceTester()
	// exercises.RemoveElementFromArrayTester()
	// exercises.RemoveDuplicatesFromArrayTester()
	// exercises.MergeTwoListsTester()
	// exercises.IsValidParenthesesTester()
	// exercises.LongestCommonPrefixTester()
	// exercises.RomanToIntTester()
	// exercises.IsPalindromeTester()
	// exercises.TwoSumsTester()
}
